
  
name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      # - name: set up JDK 11
      #   uses: actions/setup-java@v3
      #   with:
      #     java-version: '11'

      - name: Run lint
        # run: ./gradlew lint
        # - uses: yutailang0119/action-android-lint@v3
        #   with:
        #     report-path: build/reports/*.xml
        run: ./gradlew lintDebug --stacktrace
        continue-on-error: true

      - name: Upload html test report
        uses: actions/upload-artifact@v2
        with:
          name: lint.html
          path: app/build/reports/*.html
          # path: app/build/reports/lint-results-debug.html