
  
name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Run lint test
        run:  echo Run lint test
      #   run:  ./gradlew lint #./gradlew lintDebug --stacktrace
      #   continue-on-error: true

      # - name: Upload test report
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: lint.html
      #     path: app/build/reports/lint-results.html #*.html /lint-results-debug.html

  unit-test:
    needs: [lint-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Run unit tests
        run: echo Run unit tests
      #   run: ./gradlew test #bash ./gradlew test --stacktrace 

      # - name: Upload test report
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: unit_test_report
      #     path: app/build/reports/tests/testDebugUnitTest/

  instrumentation-test:
    needs: [unit-test]
    runs-on: macos-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Run espresso tests
        run: echo Run espresso tests
      #   uses: reactivecircus/android-emulator-runner@v2
      #   with:
      #     api-level: 29
      #     script: ./gradlew connectedCheck

      # - name: Upload test report
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: instrumentation_test_report
      #     path: app/build/reports/androidTests/connected/

  static-code-analysis:
    needs: [instrumentation-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: SonarCloud Scan
        run: ./gradlew app:sonarqube -Dsonar.login=${{ secrets.SONAR_TOKEN }} -Pandroid.debug.obsoleteApi=true --stacktrace --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        


