
  
name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      # - name: set up JDK 11
      #   uses: actions/setup-java@v2
      #   with:
      #       java-version: '11'
      #       distribution: 'temurin'
      #       cache: gradle

      # - name: Grant execute permission for gradlew
      #   run: chmod +x gradlew

      - name: Run lint
        run:  ./gradlew lint #./gradlew lintDebug --stacktrace
        continue-on-error: true

      - name: Upload html test report
        uses: actions/upload-artifact@v3
        with:
          name: lint.html
          path: app/build/reports/lint-results.html #*.html /lint-results-debug.html

  unit-test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Run tests
        run: ./gradlew test #bash ./gradlew test --stacktrace 

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: unit_test_report
          path: app/build/reports/tests/testDebugUnitTest/

      - name: Debug
        run: ls -la app/build/reports/tests/testDebugUnitTest/
        


